#! /bin/sh

if [ -n "${GIT_DIR}" ]; then
  HOOKS_DIR="./${GIT_DIR}/hooks/"
else
  HOOKS_DIR="./"
fi
. "${HOOKS_DIR}common"

if isBranch "master" || isBranch "develop"; then
  echo "WARNING: Could not commit to `getBranch`."
  exit 1
fi

exit 0
